######################################################################
# Automatically generated by qmake (3.0) Wed Mar 22 16:19:43 2017
######################################################################

TEMPLATE = app
TARGET = arcanum
INCLUDEPATH += .

QT += gui widgets webengine webenginewidgets webchannel

# Input
SOURCES += src/main.cpp
INSTALLS += target
target.path = /${out}/bin
